services:
  booking-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    networks:
      - hotel-network

networks:
  hotel-network:
    external: true 
