services:
  booking-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - billing-service
    networks:
      - hotel-network

networks:
  hotel-network:
